### ISSUE TITLE
Add option to show broken/not recognized destination_sign relations

### ISSUE THREAD

**Issue by fidelis-assis** [mueschel/OsmDestinationSigns#10]
I was not able to find an option to show broken destination_sign relations (with perhaps a red baloon with a croiss check) so I'm asking if it'd be possible to add such a facility.  It'd be nice for finding and fixing broken relations.

**Comment by mueschel** [comment]
Could you show an example of a broken relation you want to find?
What exactly is broken with them?

Currently there is a question mark shown instead of the direction arrow in case the geometry of to/from/intersection members can't be determined properly. This only works after you clicked on a marker, not on the map itself.

Unfortunately I can't test all the relations automatically before showing the marker on the map - this would require too much computation and too many accesses to the API. If we can define what checks need to be done to verify a relation, we could try to ask for some support in one of the QA tools like OSMI.

**Comment by fidelis-assis** [comment]
First, your tool is very nice, it helps me a lot to verify relations I map, thanks! But I noticed that destination_sign relations whose intersection member is a way (not a node) are not shown. Perhaps your overpass query doesn' t even download them, so they can't be shown even if just to show "broken" or "not orthodox"  relations. The original proposal (rejected but widely used) says that intersection member must be a node but some mappers use way for intersection (sometimes tagged as 'via'), what became  became a reasobly common usage.  It'd be interesting to show them as, say, "broken/not ortodox", or consider them OK and show them normally. 

There are other types of broken destination_sign relations, such as those with more than 1 "to" member (really broken). The extra 'to" is usually added by iD editor itself when a mapper splits a "to" member - I opened a ticket for this bug but it's not fixed yet.

**Comment by mueschel** [comment]
Let's break this down into categories:

- relations with a sign or intersection node are already shown on the map, no matter which additional via/intersection ways they have
- accepting 'via' nodes should be simple
- accepting a way as via or intersection will be some work
- multiple 'to' ways are already accepted, but may result in a question mark instead of a direction arrow. (Note that this can be resolved automatically if one of the 'to' ways ends at a 'intersection' node as it should be)

Checking any of these issues and show error markers on the map is out of scope for this tool - it would require to download the whole relation and check its members before displaying them which takes too much time.
To find strange relations I suggest to use Overpass, e.g. like this: https://overpass-turbo.eu/s/1jOe

**Comment by fidelis-assis** [comment]
OK, thanks for your answer. It was just a suggestion and I understand you consider it out of scope.

**Comment by fidelis-assis** [comment]
And thanks for the overpass query, nice!

**Comment by mueschel** [comment]
Well... I might not be able to check relations, but I figured I can show all remaining relations which aren't shown with regular markers.

http://osm.janmichel.eu/destinationsign/example/#zoom=18&lat=49.997382&lon=9.19536

- [x] accepting 'via' nodes should be simple
- [x]  show error markers for everything not shown previously
- [ ] accepting a way as via or intersection

**Comment by fidelis-assis** [comment]
Great! This will be a big help in fixing problematic relations.
Many thanks.
